version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: cimg/node:16.15.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setting Up the enviorment
          command: sudo apt-get update
      - run:
          name: node version check
          command: node --version
      - run:
          name: npn packages downloading
          command: npm install
      - run:
          name: Test execution and report genaration 
          command: npm test -- --reporter mochawesome --dev